# schema.yml

version: 2

sources:
  - name: gz_raw_data
    tables:
      - name : raw_gz_product
        description: products of Greenweez
      - name: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
      - name: raw_gz_ship
        description: ships of Greenweez
        columns:
          - name: orders_id
            tests: 
              - not_null
              - unique